package ossein

import (
	"go/format"
	"log/slog"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// The exported Wiring* declarations below exist only for wiring generation
// tests; generation resolves their symbols and package paths through
// reflection and runtime function metadata.

type WiringStore interface {
	WiringFind() string
}

type WiringRepository struct{}

func (*WiringRepository) WiringFind() string { return "" }

// NewWiringRepository is a test constructor for wiring generation.
func NewWiringRepository() *WiringRepository { return &WiringRepository{} }

type WiringService struct {
	store  WiringStore
	logger *slog.Logger
}

// NewWiringService is a test constructor for wiring generation.
func NewWiringService(store WiringStore, logger *slog.Logger) (*WiringService, error) {
	return &WiringService{store: store, logger: logger}, nil
}

type WiringHandler struct {
	service *WiringService
}

// NewWiringHandler is a test constructor for wiring generation.
func NewWiringHandler(service *WiringService) *WiringHandler {
	return &WiringHandler{service: service}
}

func newWiringTestApp(t *testing.T) *App {
	t.Helper()
	app := New()
	if err := Instance(app, slog.Default()); err != nil {
		t.Fatal(err)
	}
	if err := ProvideAs[WiringStore](app, NewWiringRepository); err != nil {
		t.Fatal(err)
	}
	if err := app.Provide(NewWiringService); err != nil {
		t.Fatal(err)
	}
	if err := app.Provide(NewWiringHandler, Transient()); err != nil {
		t.Fatal(err)
	}
	return app
}

func TestGenerateWiringEmitsExplicitGraph(t *testing.T) {
	app := newWiringTestApp(t)

	source, err := GenerateWiring(app, "wiring")
	if err != nil {
		t.Fatal(err)
	}
	text := string(source)

	if _, err := format.Source(source); err != nil {
		t.Fatalf("generated source does not format: %v\n%s", err, text)
	}

	// gofmt column-aligns declarations; collapse runs of spaces and tabs so
	// assertions can use single spacing.
	normalized := regexp.MustCompile(`[ \t]+`).ReplaceAllString(text, " ")

	for _, expected := range []string{
		"// Code generated by ossein wire. DO NOT EDIT.",
		"package wiring",
		"type Services struct {",
		"Logger *slog.Logger",
		"WiringService *ossein.WiringService",
		"WiringStore ossein.WiringStore",
		"func Wire(logger *slog.Logger) (*Services, error) {",
		"wiringStore := ossein.NewWiringRepository()",
		"wiringService, err := ossein.NewWiringService(wiringStore, logger)",
		"func (s *Services) NewWiringHandler() *ossein.WiringHandler {",
		"return ossein.NewWiringHandler(s.WiringService)",
	} {
		if !strings.Contains(normalized, expected) {
			t.Fatalf("generated source is missing %q:\n%s", expected, text)
		}
	}

	// The repository construction must precede the service that consumes it.
	if strings.Index(text, "NewWiringRepository") > strings.Index(text, "NewWiringService") {
		t.Fatalf("constructors are not in dependency order:\n%s", text)
	}

	// The error-returning constructor must be checked and wrapped.
	if !strings.Contains(text, "if err != nil {") {
		t.Fatalf("generated source does not check constructor errors:\n%s", text)
	}
}

func TestGenerateWiringIsDeterministic(t *testing.T) {
	first, err := GenerateWiring(newWiringTestApp(t), "wiring")
	if err != nil {
		t.Fatal(err)
	}
	second, err := GenerateWiring(newWiringTestApp(t), "wiring")
	if err != nil {
		t.Fatal(err)
	}
	if string(first) != string(second) {
		t.Fatalf("generation is not deterministic:\n%s\n---\n%s", first, second)
	}
}

func TestGenerateWiringEmptyContainer(t *testing.T) {
	source, err := GenerateWiring(New(), "wiring")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(source), "return &Services{}, nil") {
		t.Fatalf("empty container wiring = %s", source)
	}
}

func TestGenerateWiringRejectsClosureConstructors(t *testing.T) {
	app := New()
	if err := app.Provide(func() *WiringRepository { return nil }); err != nil {
		t.Fatal(err)
	}
	if _, err := GenerateWiring(app, "wiring"); err == nil ||
		!strings.Contains(err.Error(), "named top-level function") {
		t.Fatalf("closure constructor error = %v", err)
	}
}

func TestGenerateWiringRejectsUnexportedConstructors(t *testing.T) {
	app := New()
	if err := app.Provide(newWiringUnexported); err != nil {
		t.Fatal(err)
	}
	if _, err := GenerateWiring(app, "wiring"); err == nil ||
		!strings.Contains(err.Error(), "exported") {
		t.Fatalf("unexported constructor error = %v", err)
	}
}

func newWiringUnexported() *WiringRepository { return &WiringRepository{} }

// NewWiringGeneric is a generic test constructor for wiring generation.
func NewWiringGeneric[T any]() *WiringRepository { return &WiringRepository{} }

func TestGenerateWiringRejectsGenericConstructors(t *testing.T) {
	app := New()
	if err := app.Provide(NewWiringGeneric[int]); err != nil {
		t.Fatal(err)
	}
	if _, err := GenerateWiring(app, "wiring"); err == nil ||
		!strings.Contains(err.Error(), "named top-level function") {
		t.Fatalf("generic constructor error = %v", err)
	}
}

func TestGenerateWiringRejectsUnsupportedDependencyTypes(t *testing.T) {
	app := New()
	if err := Instance(app, func() {}); err != nil {
		t.Fatal(err)
	}
	if _, err := GenerateWiring(app, "wiring"); err == nil {
		t.Fatal("expected unsupported type error")
	}
}

func TestGenerateWiringValidatesGraphFirst(t *testing.T) {
	app := New()
	if err := app.Provide(NewWiringService); err != nil {
		t.Fatal(err)
	}
	if _, err := GenerateWiring(app, "wiring"); err == nil ||
		!strings.Contains(err.Error(), "unregistered") {
		t.Fatalf("missing dependency error = %v", err)
	}
}

func TestWriteWiringFile(t *testing.T) {
	app := newWiringTestApp(t)
	path := filepath.Join(t.TempDir(), "internal", "wiring", "wiring_gen.go")

	if err := WriteWiringFile(app, path, "wiring"); err != nil {
		t.Fatal(err)
	}
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(content), "package wiring") {
		t.Fatalf("written wiring file = %s", content)
	}
}
